/** @type {import('tailwindcss').Config} */
export default {
	darkMode: ['class'],
	content: ['./entrypoints/**/*.{html,ts,tsx}', './components/**/*.tsx'],
	theme: {
		container: {
			center: true,
			padding: '2rem',
			screens: {
				'2xl': '1400px',
			},
		},
		extend: {
			fontSize: {
				xs: ['0.75em', '1em'],
				sm: ['0.875em', '1.25em'],
				base: ['1em', '1.5em'],
				lg: ['1.125em', '1.75em'],
				xl: ['1.25em', '1.75em'],
				'2xl': ['1.5em', '2em'],
				'3xl': ['1.875em', '2.25em'],
				'4xl': ['2.25em', '2.5em'],
				'5xl': ['2.625em', '1'],
			},
			borderRadius: {
				none: '0',
				xs: '0.125em',
				sm: '0.25em',
				DEFAULT: '4px',
				md: '0.375em',
				lg: '0.5em',
				large: '12px',
				full: '9999px',
			},
			spacing: {
				0: '0em',
				0.5: '0.125em',
				1: '0.25em',
				2: '0.5em',
				3: '0.75em',
				4: '1em',
				5: '1.25em',
				6: '1.5em',
				7: '1.75em',
				8: '2em',
				9: '2.25em',
				10: '2.5em',
				11: '2.75em',
				12: '3em',
				14: '3.5em',
				16: '4em',
				20: '5em',
				24: '6em',
				28: '7em',
				32: '8em',
				36: '9em',
				40: '10em',
				44: '11em',
				48: '12em',
				52: '13em',
				56: '14em',
				60: '15em',
				64: '16em',
				72: '18em',
				80: '20em',
				96: '24em',
			},
			colors: {
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
			},
			borderRadius: {
				lg: `var(--radius)`,
				md: `calc(var(--radius) - 2px)`,
				sm: 'calc(var(--radius) - 4px)',
			},
			fontFamily: {
				sans: ['var(--font-sans)'],
			},
			keyframes: {
				'accordion-down': {
					from: { height: '0' },
					to: { height: 'var(--radix-accordion-content-height)' },
				},
				'accordion-up': {
					from: { height: 'var(--radix-accordion-content-height)' },
					to: { height: '0' },
				},
			},
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
			},
		},
	},
	plugins: [require('tailwindcss-animate')],
}
